{% set name = "xpublish-edr" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xpublish_edr-{{ version }}.tar.gz
  sha256: 3856e261004025fece803ddd94c9984930225616433e448a2b86b2d4e21d8c74

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.7
    - shapely
    - xarray
    - xpublish <0.4.0,>=0.3.0

test:
  imports:
    - xpublish_edr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xpublish-community/xpublish-edr
  summary: Xpublish plugin for the OGC EDR API
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - abkfenris
